# Generated by Django 4.1.1 on 2023-03-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
