# Generated by Django 4.1.1 on 2023-03-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='floors',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='property_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
