# Generated by Django 4.1.1 on 2023-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_floors_product_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='floors',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='garage',
            field=models.FloatField(default=''),
        ),
    ]
