# Generated by Django 4.1.1 on 2023-03-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_floors_alter_product_garage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellingprice',
            new_name='min_price',
        ),
    ]
