# Generated by Django 4.1.1 on 2023-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('bungalow', 'bungalow'), ('house', 'house'), ('land', 'land'), ('villa', 'villa'), ('guest', 'guest')], default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('map_location', models.TextField(default='')),
                ('property_price', models.FloatField()),
                ('year_build', models.IntegerField()),
                ('property_for', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], default='', max_length=30)),
                ('description', models.TextField()),
                ('no_of_floors', models.IntegerField(default='')),
                ('no_of_rooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('area_sqft', models.FloatField()),
                ('parking', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=100)),
                ('photo1', models.ImageField(upload_to='product/')),
                ('photo2', models.ImageField(upload_to='product/')),
                ('photo3', models.ImageField(upload_to='product/')),
                ('photo4', models.ImageField(upload_to='product/')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'porperty',
            },
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
