# Generated by Django 4.1.1 on 2023-03-10 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_properties_no_of_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='photo',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_by',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
    ]
