# Generated by Django 4.1.1 on 2023-03-11 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_blogs_description_alter_blogs_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='blog/')),
                ('post_by', models.CharField(default='Admin', max_length=50)),
                ('post_on', models.DateField(default=datetime.date(2023, 3, 11))),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
