# Generated by Django 4.1.1 on 2023-03-12 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_blog_description_alter_properties_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 3, 12)),
        ),
    ]
