# Generated by Django 4.1.1 on 2023-03-16 05:03

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_faq_alter_blog_post_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='photo3',
            field=models.ImageField(upload_to='properties/'),
        ),
    ]
