# Generated by Django 4.1.1 on 2023-04-18 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_blog_post_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
        migrations.AlterModelTable(
            name='properties',
            table='properties',
        ),
    ]
