# Generated by Django 4.1.1 on 2023-04-19 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_blog_post_on_alter_properties_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 19)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='area_sqft',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_price',
            field=models.CharField(max_length=50),
        ),
    ]
